spring.application.name=gerenciamente-de-custos



# ============== Configurações do banco de dados H2 =================
// Define o caminho do banco de dados H2 (será criado um arquivo chamado "gerenciamente_de_custos_db" na pasta "data" do projeto)
spring.datasource.url=jdbc:h2:file:./data/gerenciamente_de_custos_db  
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
// Configura o Hibernate para atualizar o esquema do banco de dados automaticamente com base nas entidades definidas no código
spring.jpa.hibernate.ddl-auto=update  